name: Build macOS

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-macos:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-14
            arch: arm64
          - os: macos-13
            arch: x64
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            ainative-studio/package-lock.json
            ainative-studio/build/package-lock.json
      - name: Install build dependencies
        working-directory: ainative-studio/build
        run: |
          for i in {1..5}; do # try 5 times
            npm ci && break
            if [ $i -eq 5 ]; then
              echo "npm ci in build/ failed too many times" >&2
              exit 1
            fi
            echo "npm ci in build/ failed $i, trying again..."
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        working-directory: ainative-studio
        run: |
          for i in {1..5}; do # try 5 times
            npm ci && break
            if [ $i -eq 5 ]; then
              echo "npm ci failed too many times" >&2
              exit 1
            fi
            echo "npm ci failed $i, trying again..."
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Cache node build cache
        uses: actions/cache@v4
        with:
          path: |
            ainative-studio/node_modules/.cache
            ainative-studio/extensions/*/node_modules/.cache
          key: node-cache-${{ runner.os }}-${{ matrix.arch }}-${{ hashFiles('ainative-studio/package-lock.json') }}
          restore-keys: |
            node-cache-${{ runner.os }}-${{ matrix.arch }}-
            node-cache-${{ runner.os }}-
      - name: Cache gulp cache
        uses: actions/cache@v4
        with:
          path: ~/.gulp-cache
          key: ${{ runner.os }}-gulp-${{ hashFiles('ainative-studio/package-lock.json', 'ainative-studio/build/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-gulp-
      - name: Build and minify client
        working-directory: ainative-studio
        run: |
          npm run buildreact
          npm run gulp vscode-darwin-${{ matrix.arch }}-min
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Package
        working-directory: ainative-studio
        run: npm run gulp vscode-darwin-${{ matrix.arch }}-min-ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Verify build output
        run: |
          if [ ! -d "VSCode-darwin-${{ matrix.arch }}" ] && [ ! -d "../VSCode-darwin-${{ matrix.arch }}" ]; then
            echo "::error::Build output directory not found!"
            echo "Contents of ainative-studio directory:"
            ls -la
            echo "Contents of parent directory:"
            ls -la ../
            exit 1
          fi
        working-directory: ainative-studio
      - name: Create archive
        run: |
          if [ -d "VSCode-darwin-${{ matrix.arch }}" ]; then
            cd VSCode-darwin-${{ matrix.arch }}
            tar --warning=no-file-changed -czf ../ainative-studio-darwin-${{ matrix.arch }}.tar.gz . || true
          elif [ -d "../VSCode-darwin-${{ matrix.arch }}" ]; then
            cd ../VSCode-darwin-${{ matrix.arch }}
            tar --warning=no-file-changed -czf ainative-studio-darwin-${{ matrix.arch }}.tar.gz . || true
            mv ainative-studio-darwin-${{ matrix.arch }}.tar.gz ainative-studio/
          fi
        working-directory: ainative-studio
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ainative-studio-darwin-${{ matrix.arch }}
          path: ainative-studio/ainative-studio-darwin-${{ matrix.arch }}.tar.gz
          retention-days: 7
