name: Build Linux

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            ainative-studio/package-lock.json
            ainative-studio/build/package-lock.json
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libkrb5-dev
      - name: Install build dependencies
        working-directory: ainative-studio/build
        run: |
          for i in {1..5}; do # try 5 times
            npm ci && break
            if [ $i -eq 5 ]; then
              echo "npm ci in build/ failed too many times" >&2
              exit 1
            fi
            echo "npm ci in build/ failed $i, trying again..."
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        working-directory: ainative-studio
        run: |
          for i in {1..5}; do # try 5 times
            npm ci && break
            if [ $i -eq 5 ]; then
              echo "npm ci failed too many times" >&2
              exit 1
            fi
            echo "npm ci failed $i, trying again..."
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Cache gulp cache
        uses: actions/cache@v3
        with:
          path: ~/.gulp-cache
          key: ${{ runner.os }}-gulp-${{ hashFiles('ainative-studio/package-lock.json', 'ainative-studio/build/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-gulp-
      - name: Build
        working-directory: ainative-studio
        run: |
          npm run buildreact
          npm run gulp compile-build-with-mangling
          npm run gulp minify-vscode
          npm run gulp vscode-linux-x64-min-ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Verify build output
        run: |
          if [ ! -d "VSCode-linux-x64" ]; then
            echo "::error::Build output directory not found!"
            exit 1
          fi
        working-directory: ainative-studio
      - name: Create archive
        working-directory: ainative-studio/VSCode-linux-x64
        run: tar -czf ../../ainative-studio-linux-x64.tar.gz .
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ainative-studio-linux-x64
          path: ainative-studio/ainative-studio-linux-x64.tar.gz
          retention-days: 7
