name: Release (Parallel Simple)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The git tag to create a release for (e.g. v1.2.3)'
        required: true
        type: string

jobs:
  build-linux:
    uses: ./.github/workflows/build-linux-parallel-simple.yml

  build-windows:
    uses: ./.github/workflows/build-windows-parallel-simple.yml

  build-macos:
    uses: ./.github/workflows/build-macos-parallel-simple.yml

  create-release:
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows, build-macos]
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./artifacts/ainative-studio-linux-x64/*.tar.gz
            ./artifacts/ainative-studio-win32-x64/*.zip
            ./artifacts/ainative-studio-darwin-arm64/*.tar.gz
            ./artifacts/ainative-studio-darwin-x64/*.tar.gz
          draft: false
          prerelease: contains(github.event.inputs.tag, 'alpha') || contains(github.event.inputs.tag, 'beta') || contains(github.event.inputs.tag, 'rc')
          generate_release_notes: true
          tag_name: ${{ github.event.inputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}